(()=>{const polish=document.createElement('link');polish.rel='stylesheet';polish.href='/css/executive-polish.css?v=20260902-exec4';document.head.appendChild(polish)})();
(()=>{if(document.querySelector('link[href*="strategy-refresh.css"]'))return;const strategy=document.createElement('link');strategy.rel='stylesheet';strategy.href='/css/strategy-refresh.css?v=20260902-strategy1';document.head.appendChild(strategy)})();
(()=>{const style=document.createElement('style');style.textContent=`@media(max-width:780px){.site-header{position:relative!important;inset:auto!important;background:#031431;overflow:visible!important}.nav{position:relative!important;z-index:1000!important}.menu{position:relative!important;z-index:1002!important}.nav-links{z-index:1001!important}.site-update{position:relative!important;z-index:1!important}.hero-content{padding-top:70px!important}.page-hero{padding-top:70px!important}}@media(max-width:520px){.hero-content{padding-top:60px!important}.page-hero{padding-top:60px!important}}`;document.head.appendChild(style)})();
const menu=document.querySelector('[data-menu]');
const nav=document.querySelector('.nav-links');
if(menu&&nav){menu.addEventListener('click',()=>{nav.classList.toggle('open');menu.setAttribute('aria-expanded',nav.classList.contains('open'));});nav.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{nav.classList.remove('open');menu.setAttribute('aria-expanded','false')}));document.addEventListener('keydown',e=>{if(e.key==='Escape'&&nav.classList.contains('open')){nav.classList.remove('open');menu.setAttribute('aria-expanded','false');menu.focus()}});}
const normalizePath=value=>{const url=new URL(value,location.origin);return url.pathname.replace(/\/index\.html$/,'/').replace(/\/+$/,'/')||'/';};
const page=normalizePath(location.pathname);document.querySelectorAll('.nav-links a').forEach(a=>{if(normalizePath(a.href)===page)a.classList.add('active');});
(()=>{document.querySelectorAll('a[href="/news/"],a[href="/news"],a[href="news.html"]').forEach(a=>{const t=a.textContent.trim().toUpperCase();if(t==='NEWS'||t==='COMPANY UPDATES')a.textContent=t==='NEWS'?'INSIGHTS':'Insights';});})();
(()=>{if(page!=='/careers/')return;const cards=[...document.querySelectorAll('.career-job-card')];const vp=cards.find(card=>/Vice President of Sales/i.test(card.textContent));if(!vp)return;const heading=vp.querySelector('h3');if(!heading||heading.querySelector('.interviewing-badge'))return;const badge=document.createElement('span');badge.className='interviewing-badge';badge.textContent='INTERVIEWING';heading.appendChild(badge);const style=document.createElement('style');style.textContent=`.interviewing-badge{display:inline-flex;align-items:center;margin-left:12px;padding:5px 9px;border:1px solid rgba(38,201,255,.42);border-radius:999px;background:rgba(38,201,255,.08);color:#087fb0;font-size:9px;font-weight:800;line-height:1;letter-spacing:.12em;vertical-align:middle;white-space:nowrap}.interviewing-badge::before{content:'';width:6px;height:6px;margin-right:6px;border-radius:50%;background:#16a36a;box-shadow:0 0 0 3px rgba(22,163,106,.10)}@media(max-width:520px){.interviewing-badge{margin-left:0;margin-top:9px;width:max-content;display:flex}}`;document.head.appendChild(style)})();
document.querySelectorAll('form[data-mailto]').forEach(form=>{form.addEventListener('submit',e=>{e.preventDefault();const data=new FormData(form),subject=data.get('subject')||'Website inquiry',lines=[];for(const[k,v]of data.entries()){if(k!=='subject'&&v)lines.push(`${k}: ${v}`)}const href=`mailto:${form.dataset.mailto}?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(lines.join('\n'))}`,msg=form.querySelector('.form-msg');if(msg)msg.textContent='Opening your email app with the completed inquiry…';window.location.href=href;});});
const year=document.querySelector('[data-year]');if(year)year.textContent=new Date().getFullYear();
const reduceMotion=window.matchMedia('(prefers-reduced-motion: reduce)').matches;if(!reduceMotion&&'IntersectionObserver'in window){document.documentElement.classList.add('motion-ready');const motionTargets=document.querySelectorAll(['.split-image','.image-strip-main','.image-strip-side','.image-strip-detail','.workspace','.feature','.card','.cap','.verification-card','.verification-link','.foundation-card','.career-job-card','.executive-card','.benefit-card','.intelligence-card','.security-card','.intelligence-gateway-card','.insights-track','.ecosystem-compact-note'].join(','));const observer=new IntersectionObserver(entries=>{entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('is-visible');observer.unobserve(entry.target)}})},{threshold:.12,rootMargin:'0px 0px -6%'});motionTargets.forEach(target=>observer.observe(target));}
(()=>{const footerGrid=document.querySelector('.footer-grid');if(!footerGrid)return;const style=document.createElement('style');style.textContent=`.footer-accordion-toggle{display:none}.footer-accordion-panel{display:block}@media(max-width:780px){.footer{padding:38px 0 18px}.footer-grid{display:grid;grid-template-columns:1fr!important;gap:0!important}.footer-brand{grid-column:1/-1!important;padding-bottom:20px}.footer-brand p{max-width:360px;margin:5px 0}.footer-accordion-group{border-top:1px solid rgba(255,255,255,.11)}.footer-accordion-group:last-child{border-bottom:1px solid rgba(255,255,255,.11)}.footer-accordion-group>h4{display:none}.footer-accordion-toggle{display:flex;width:100%;min-height:50px;align-items:center;justify-content:space-between;gap:16px;padding:0;border:0;background:transparent;color:#fff;text-align:left;font-size:11px;font-weight:800;letter-spacing:.09em;text-transform:uppercase;cursor:pointer}.footer-accordion-toggle::after{content:'+';font-size:21px;font-weight:300;line-height:1;color:#72d4ff}.footer-accordion-group.is-open .footer-accordion-toggle::after{content:'−'}.footer-accordion-panel{display:grid;grid-template-rows:0fr;overflow:hidden;transition:grid-template-rows .25s ease}.footer-accordion-panel-inner{min-height:0;overflow:hidden}.footer-accordion-group.is-open .footer-accordion-panel{grid-template-rows:1fr}.footer-accordion-group.is-open .footer-accordion-panel-inner{padding:0 0 15px}.footer-accordion-panel a{margin:0!important;padding:7px 0;font-size:11px}.copyright{margin-top:24px!important}}@media(prefers-reduced-motion:reduce){.footer-accordion-panel{transition:none!important}}`;document.head.appendChild(style);[...footerGrid.children].forEach((group,index)=>{if(group.classList.contains('footer-brand'))return;const heading=group.querySelector(':scope > h4');if(!heading)return;group.classList.add('footer-accordion-group');const button=document.createElement('button'),panel=document.createElement('div'),inner=document.createElement('div'),panelId=`footer-panel-${index}`;button.type='button';button.className='footer-accordion-toggle';button.textContent=heading.textContent.trim();button.setAttribute('aria-expanded','false');button.setAttribute('aria-controls',panelId);panel.className='footer-accordion-panel';panel.id=panelId;inner.className='footer-accordion-panel-inner';[...group.children].forEach(node=>{if(node!==heading)inner.appendChild(node)});panel.appendChild(inner);heading.insertAdjacentElement('afterend',button);group.appendChild(panel);button.addEventListener('click',()=>{const willOpen=!group.classList.contains('is-open');footerGrid.querySelectorAll('.footer-accordion-group.is-open').forEach(openGroup=>{if(openGroup!==group){openGroup.classList.remove('is-open');const openButton=openGroup.querySelector('.footer-accordion-toggle');if(openButton)openButton.setAttribute('aria-expanded','false')}});group.classList.toggle('is-open',willOpen);button.setAttribute('aria-expanded',String(willOpen))})})})();
(()=>{if(document.querySelector('link[href*="verification.css"]')){const v=document.createElement('link');v.rel='stylesheet';v.href='/css/verification.css?v=20260902-verify2';document.head.appendChild(v)}})();
