from corporate_alignment_common import repl

def run():
    # HOME
    repl('index.html', '<strong>DApps Platform USA continues to expand its U.S. operations, leadership team, and digital capabilities.</strong>', '<strong>DApps Platform Inc. continues to expand U.S. market operations under the DApps Platform USA business designation.</strong>')
    repl('index.html', 'DApps Platform USA is the independently governed U.S. operating organization of DApps Platform Inc., with its U.S. operating presence being developed in Los Angeles. DApps Platform USA maintains its own U.S. leadership and Board oversight, while DApps Platform Inc. serves as the underlying legal entity for applicable employment, contracting, and corporate obligations.', 'DApps Platform USA is the U.S. market-facing business brand and operating designation of DApps Platform Inc., a Delaware corporation. U.S. market activities are being developed in Los Angeles under this designation, while DApps Platform Inc. remains the legal entity for applicable employment, contracting, and corporate obligations.')
    repl('index.html', 'Our U.S. organization is being developed around professional collaboration, flexible working practices, and the operating discipline required to build long-term digital financial infrastructure.', 'Our U.S. market operations are being developed around professional collaboration, flexible working practices, and the operating discipline required to build long-term digital financial infrastructure.', False)
    repl('index.html', 'DApps Platform USA should not be read as a statement that every similarly named entity is the same legal entity.', 'DApps Platform USA is the U.S. business and operating designation of DApps Platform Inc.; references to other similarly named entities should not be read as establishing that they are the same legal entity or have the same relationship to Trust Wallet.')

    # ABOUT
    repl('about/index.html', 'For clarity, this website uses the phrase “Trust Wallet ecosystem context” rather than asserting that DApps Platform USA is identical to, or the legal operator of, every entity associated with Trust Wallet. Any future corporate relationship will be described according to supporting legal documentation.', 'For clarity, this website uses the phrase “Trust Wallet ecosystem context” rather than asserting that DApps Platform USA is identical to, or the legal operator of, every entity associated with Trust Wallet. Any additional relationship with Trust Wallet-associated legal entities will be described according to supporting legal documentation.')
    repl('about/index.html', '<h3>U.S. Operating Structure</h3><p>DApps Platform USA is the independently governed U.S. operating organization of DApps Platform Inc. It is being developed with its own U.S. leadership structure, operating responsibilities, decision-making framework, and dedicated Board oversight in Los Angeles, California.</p><p>DApps Platform Inc., a Delaware corporation, is the underlying legal entity through which applicable U.S. employment, contracting, and corporate obligations are undertaken. References on this website to DApps Platform USA describe the U.S. operating and governance organization and should not be read as a statement that DApps Platform USA is a separately incorporated legal entity.</p>', '<h3>U.S. Market Structure</h3><p><strong>DApps Platform USA</strong> is the Company-authorized U.S. market-facing business brand, trade name, and operating designation of <strong>DApps Platform Inc.</strong> for United States activities. It may be used for U.S. business development, marketing, partnerships, recruiting, customer and business communications, vendor relationships, and other Company-approved activities.</p><p><strong>DApps Platform Inc.</strong>, a Delaware corporation, remains the legal entity for applicable employment, contracting, and corporate obligations. DApps Platform USA does not constitute a separate legal entity unless it is separately incorporated or expressly designated as such in a written Company instrument. The signed Corporate Authorization supporting this structure is available on the <a href="/company-verification/">Company Verification</a> page.</p>')

    # CAREERS
    repl('careers/index.html', 'DApps Platform is establishing the teams, governance, technology, controls, commercial capabilities, and operating disciplines required for its developing U.S. market operations.', 'DApps Platform Inc. is building its U.S. market teams, governance, technology, controls, commercial capabilities, and operating disciplines under the DApps Platform USA business designation.')
    repl('careers/index.html', 'Selected leaders will not simply inherit mature functions. They will have the opportunity to help define mandates, establish frameworks, recruit capabilities, influence priorities, and create operating standards designed to scale.', 'Selected leaders will have the opportunity to help define mandates, establish frameworks, recruit capabilities, influence priorities, and create operating standards designed to scale within the Company’s U.S. market operations.')
    repl('careers/index.html', 'That requires experienced people who are comfortable with accountability, ambiguity, independent judgment, and close access to senior decision-makers.', 'That requires experienced people who are comfortable with accountability, independent judgment, and close access to senior decision-makers, while working within clearly identified legal and contracting authority.')
    repl('careers/index.html', '<div class="careers-label">U.S. EMPLOYMENT STRUCTURE</div><h2>One U.S. operating organization. Clear legal responsibility.</h2></div><div class="careers-intro-copy"><p>DApps Platform USA is the independently governed U.S. operating organization in which these U.S. roles are structured, including dedicated U.S. leadership and Board oversight.</p><p>DApps Platform Inc. is the underlying legal entity and may serve as the legal employer and contracting party for applicable U.S. employment agreements.</p><p>This structure allows executive roles to operate within DApps Platform USA while keeping formal legal and contractual obligations clearly identified in the applicable written agreement.</p>', '<div class="careers-label">U.S. EMPLOYMENT STRUCTURE</div><h2>Clear U.S. identity. Clear legal responsibility.</h2></div><div class="careers-intro-copy"><p><strong>DApps Platform USA</strong> is the U.S. market-facing business brand and operating designation of <strong>DApps Platform Inc.</strong> for Company-authorized U.S. activities, including recruiting and talent acquisition.</p><p><strong>DApps Platform Inc.</strong>, a Delaware corporation, is the applicable legal employer and contracting party for U.S. executive employment agreements unless another legal entity is expressly designated in writing.</p><p>U.S. executives may hold DApps Platform USA titles and responsibilities while their formal employment agreements are executed with DApps Platform Inc. The signed Corporate Authorization can be reviewed on the <a href="/company-verification/">Company Verification</a> page.</p>')
    repl('careers/index.html', 'Roles with meaningful ownership in our developing U.S. market operations.', 'Roles with meaningful ownership in the Company’s developing U.S. market operations.', False)

    # COMPANY VERIFICATION
    repl('company-verification/index.html', 'A clear statement of what DApps Platform communicates publicly today, how information should be interpreted, and how corporate disclosures will develop as the U.S. organization advances.', 'A clear statement of the legal entity, U.S. business designation, authorized representatives, and supporting corporate authorization for United States market activities.', False)
    repl('company-verification/index.html', '<div class="verification-copy"><p><strong>DApps Platform Inc.</strong>, a Delaware corporation, is the underlying legal entity for applicable U.S. employment, contracting, and corporate obligations.</p><p><strong>DApps Platform USA</strong> is the independently governed U.S. operating organization through which the Company is developing its U.S. leadership, operating capabilities, and business activities in Los Angeles, California. DApps Platform USA maintains its own U.S. leadership framework and dedicated Board oversight.</p><p><strong>DApps Platform USA Board</strong> is the dedicated governance body for the U.S. operating organization, providing strategic oversight, executive accountability, independent challenge, and escalation for material U.S. business matters.</p><p>This distinction is intended to separate operational and governance identity from legal-entity identity. DApps Platform USA should not be interpreted as a separately incorporated legal entity unless expressly stated in supporting corporate documentation.</p></div>', '<div class="verification-copy"><p><strong>DApps Platform Inc.</strong>, a Delaware corporation, is the legal entity for applicable U.S. employment, contracting, and corporate obligations.</p><p><strong>DApps Platform USA</strong> is the Company-authorized U.S. market-facing business brand, trade name, and operating designation of DApps Platform Inc. It does not constitute a separate legal entity unless separately incorporated or expressly designated in a written Company instrument.</p><p>Where the <strong>DApps Platform USA Board</strong> is referenced in executive or governance materials, it functions as an internal U.S. governance and oversight body under Company-authorized U.S. market operations; it is not the board of a separately incorporated DApps Platform USA entity.</p><p>The signed Corporate Authorization effective September 3, 2026 confirms the U.S. business designation, recruitment and contracting framework, and the authority described for U.S. executive employment agreement execution.</p></div>')
    repl('company-verification/index.html', '<article class="verification-card"><span class="number">02</span><h3>Legal &amp; Operating Structure</h3><p>DApps Platform Inc. is the underlying legal entity. DApps Platform USA is the independently governed U.S. operating organization, with dedicated U.S. leadership and Board oversight. These roles should not be treated as interchangeable legal identities.</p></article>', '<article class="verification-card"><span class="number">02</span><h3>Legal Entity &amp; U.S. Business Designation</h3><p>DApps Platform Inc. is the legal entity. DApps Platform USA is its authorized U.S. market-facing business brand and operating designation and is not a separate legal entity unless separately established in writing.</p></article>')
    repl('company-verification/index.html', '<article class="verification-card"><span class="number">05</span><h3>Employment Information</h3><p>Executive and professional roles may operate within DApps Platform USA while formal employment agreements are entered into through DApps Platform Inc. as the applicable legal employing entity. Role requirements remain subject to final written terms and applicable law.</p></article>', '<article class="verification-card"><span class="number">05</span><h3>Employment Information</h3><p>Executive and professional roles may carry DApps Platform USA titles and responsibilities while formal employment agreements are entered into through DApps Platform Inc. as the applicable legal employing and contracting entity. Role requirements remain subject to final written terms and applicable law.</p></article>')
    marker = '<section class="verification-section"><div class="container"><div class="disclosure-panel"><h3>Verification inquiries</h3>'
    auth = '<section class="verification-section"><div class="container"><div class="disclosure-panel"><div class="eyebrow">SIGNED CORPORATE RECORD</div><h3>Corporate Authorization — DApps Platform USA</h3><p><strong>DApps Platform Inc.</strong> · Delaware corporation · California Entity / File Number <strong>4190391 (C4190391)</strong></p><p>The signed Corporate Authorization is effective September 3, 2026 and authorizes “DApps Platform USA” as the Company’s U.S. market-facing business brand and operating designation, subject to the terms stated in the document.</p><p><a class="btn" href="/documents/dapps-platform-inc-corporate-authorization-dapps-platform-usa.pdf" target="_blank" rel="noopener">VIEW SIGNED CORPORATE AUTHORIZATION (PDF) →</a></p></div></div></section>' + marker
    repl('company-verification/index.html', marker, auth)
